DB接続系 & ER図(初期)
75asa/time-liner pull request #45
Opened 2020-10-16 08:40 UTC by tk-ozawa

ref #42

2020-10-16 08:45 UTC, 75asa commented
@tk-ozawa キャプチャ画像もください（出先のためコードだとみれない…）

2020-10-16 08:47 UTC, tk-ozawa commented
こちらですー
![スクリーンショット 2020-10-16 17 46 10](https://user-images.githubusercontent.com/39585292/96236860-89d8bc80-0fd7-11eb-892e-64c349a13770.png)

2020-10-16 12:26 UTC, 75asa commented
@tk-ozawa ERありがと！
このあたりいるいら項目とか喋りながらもっと話し込みたい…
contentにはslackのpayloadがはいる感じかな？
users の channel_id はいるんかな？
display_name は設定してない人もおるから real_name も考慮しないといけないかな
まとめて name とかでもよさそう
個人分報の urer_id はどのような基準で選ぶイメージ？作成者？

2020-10-16 12:26 UTC, 75asa commented
取り急ぎきになったことまとめ

2020-10-18 07:28 UTC, 75asa commented
@tk-ozawa 今日のやつでキャプチャ画像も更新お願い〜

2020-10-18 07:29 UTC, tk-ozawa commented
@75asa :done:

2020-10-19 16:27 UTC, 75asa reviewed
@tk-ozawa いくつかざっとみました🤔

2020-10-19 16:27 UTC, 75asa commented on src/entity/Timeline.ts
> +  ts: Number;
ts は string だとおもう
e.g. 1527679754.45464549

2020-10-19 16:27 UTC, 75asa commented on src/entity/Timeline.ts
> +  bindedChannelId: String;
```suggestion
  bindedChannelID: String;
```
IDなどの固有名詞は大文字でおけ

2020-10-26 01:29 UTC, tk-ozawa commented on src/entity/Timeline.ts
> +  bindedChannelId: String;
:done:

2020-10-26 01:29 UTC, tk-ozawa commented on src/entity/Timeline.ts
> +  ts: Number;
:done:

2020-10-26 02:57 UTC, 75asa commented
[eslint公式](https://eslint.org/)

2020-11-04 09:42 UTC, tk-ozawa commented
@75asa 
DB登録機能(とりあえず、個別ch投稿時に投稿ユーザーをDBに登録)実装しましたー

2020-11-04 09:57 UTC, tk-ozawa commented
@75asa 
ユーザーの管理について質問です。
現状の簡易的な仕組みであれば、ユーザーの管理は**投稿時にusersに登録、登録済であればslackIDを基にusersから情報取得**って形でいいですか？

2020-11-04 10:00 UTC, tk-ozawa commented
できればeventメソッドのmember_joined_channelイベントで監視させたかったんですけどmessageメソッド用の各middlewareと引数の有無で競合(eventメソッドにはmessageプロパティは存在せず vs messageメソッドにはｍessageプロパティが存在)してて実装できずで詰まってます、、、

2020-11-04 10:30 UTC, 75asa commented
- TLのContents いらないんじゃないか説？
- Users's Posts と TL 統合しちゃっていいんじゃないか説（テーブル）
- Users の channel_id は削除する（いらない）

2020-11-04 12:36 UTC, 75asa commented
@tk-ozawa PRの矛先を `release/beta-2.0` にしてください

2020-11-04 12:48 UTC, 75asa requested changes
@tk-ozawa いくつか気になったこと＆質問入れてます〜

2020-11-04 12:48 UTC, 75asa commented on src/entity/user.ts
> +  channelID: string;
チャネルIDいらないので削除で
それとここのエンティティだけ小文字の user.ts なのはなんででしょう 🤔

2020-11-04 12:48 UTC, 75asa commented on docs/db/er.drawio
> +                </mxCell>
ここいらないのでERからも削除

2020-11-04 12:48 UTC, 75asa commented on ormconfig.json
> +  "database": "sample",
```suggestion
  "database": "tl-poilice-man",
```

2020-11-04 12:48 UTC, 75asa commented on package.json
> +    "request": "^2.88.2",
```suggestion
```
request もう使ってないので削除おなです

2020-11-04 12:48 UTC, 75asa commented on src/entity/Timeline.ts
> +  usersPostId: ObjectID;
```suggestion
  usersPostID: ObjectID;
```

2020-11-04 12:48 UTC, 75asa commented on src/entity/Timeline.ts
> +  @JoinColumn({ name: "usersPostId" })
```suggestion
  @JoinColumn({ name: "usersPostID" })
```

2020-11-04 12:48 UTC, 75asa commented on src/entity/UsersPost.ts
> +  @OneToMany(() => TimelineEntity, (timeline) => timeline.usersPostId, {
```suggestion
  @OneToMany(() => TimelineEntity, (timeline) => timeline.usersPostID, {
```

2020-11-06 07:35 UTC, tk-ozawa commented on src/entity/user.ts
> +  channelID: string;
ファイル名、最初間違えてuser.tsにしてしまったんですけどUser.tsに変更してもgitに変更が捕捉されなくて修正できないままでです。。

2020-11-06 07:44 UTC, tk-ozawa commented on ormconfig.json
> +  "database": "sample",
:done:

2020-11-06 07:45 UTC, tk-ozawa commented on package.json
> +    "request": "^2.88.2",
:done:

2020-11-06 07:45 UTC, tk-ozawa commented on src/entity/user.ts
> +  channelID: string;
:done:

2020-11-06 07:47 UTC, tk-ozawa commented on src/entity/Timeline.ts
> +  @JoinColumn({ name: "usersPostId" })
:done:

2020-11-06 07:47 UTC, tk-ozawa commented on src/entity/UsersPost.ts
> +  @OneToMany(() => TimelineEntity, (timeline) => timeline.usersPostId, {
:done:

2020-11-06 07:47 UTC, tk-ozawa commented on src/entity/Timeline.ts
> +  usersPostId: ObjectID;
:done:

2020-11-06 08:06 UTC, tk-ozawa commented on docs/db/er.drawio
> +                </mxCell>
:done:
それに加えて、UsersPosts内のchannelIDを削除 & Users内にchannelIDが存在していなかった為追加しました

2020-11-06 08:10 UTC, tk-ozawa commented
> @tk-ozawa いくつか気になったこと＆質問入れてます〜

@75asa 
修正しましたー

2020-11-06 09:55 UTC, 75asa commented on src/entity/user.ts
> +  channelID: string;
@tk-ozawa done してなくないですか？ 🤔 
それと 僕の認識では、 User に channelID いらないとうコメントだったんですが、あってます？
むしろやっぱいる的な？

2020-11-06 09:59 UTC, 75asa commented
> @tk-ozawa PRの矛先を `release/beta-2.0` にしてください

変えました

2020-11-06 10:08 UTC, tk-ozawa commented
あすみませんそれ見逃してました…ありがとうございます！

2020-11-06 10:13 UTC, tk-ozawa commented on src/entity/user.ts
> +  channelID: string;
@75asa
drawioで該当の行を消すとUsersPosts.channelIDが消えたのでこれに従えばいいのかな？ってなってました
急ぎでやってたのでもしかしたらどこかの段階でテレコになってたかもです…… 次回出勤時修正します！

2020-11-06 10:15 UTC, 75asa commented on src/entity/user.ts
> +  channelID: string;
tk-ozawa おkですー
つぎ来たとき声かけてくださいー

2020-11-09 05:27 UTC, tk-ozawa commented
### DB接続周りの動作確認について
---現状---
- [ ] #r_<name>で発言をすると、発言したユーザーがusersテーブルの登録される
  - 尚、2回目以降の発言はユーザー情報がテーブル内で衝突します………

2020-11-11 07:54 UTC, 75asa commented
> ### DB接続周りの動作確認について
> ---現状---
> 
> * [ ]  #r_で発言をすると、発言したユーザーがusersテーブルの登録される (index.ts)
>   
>   * 尚、2回目以降の発言はユーザー情報がテーブル内で衝突します………

upsert すれば解決かな？
https://github.com/typeorm/typeorm/issues/1090

2020-11-11 07:58 UTC, 75asa commented on src/entity/user.ts
> +  channelID: string;
@tk-ozawa ここだけ修正オナです
- user.ts -> User.ts
- User.ts から channelID 削除

2020-11-11 13:49 UTC, 75asa commented
@tk-ozawa これ使ったら行けそうじゃない？
https://typeorm.delightful.studio/classes/_entity_manager_mongoentitymanager_.mongoentitymanager.html#findoneandupdate
e.g. 
```
    const mongoEntityMgr = new MongoEntityManager(await createConnection());
    const user = {
      realName: context.profile.real_name,
      displayName: context.profile.display_name,
      slackID: context.channel.creator,
    };
    const query = {
      where: {
        slackID: user.slackID,
      },
    };
    await mongoEntityMgr
      .findOneAndReplace('User', query, user, { upsert: true })
      .then(res => {
        console.log({ res });
      })
      .catch(err => {
        console.log({ err });
      });
```

2020-11-13 08:25 UTC, tk-ozawa commented
@75asa 
できませんでした。。
ちょっと探ってみます

2020-11-13 08:27 UTC, 75asa commented
> @75asa
> できませんでした。。
> ちょっと探ってみます

あ、↑のコードそのままだと失敗します、引数の指定方法が違うと思います

2020-11-13 08:28 UTC, 75asa commented
@tk-ozawa ↑ 👁️

2020-11-18 07:45 UTC, tk-ozawa commented
@75asa 
```ts
const user = {
      realName: context.profile.real_name,
      displayName: context.profile.display_name,
      slackID: context.channel.creator,
    };
    const query = {
      slackID: user.slackID,
    };
    await mongoEntityMgr
      .findOneAndReplace('users', query, user, { upsert: true })
      .then(res => {
        console.log({ res });
      })
      .catch(err => {
        console.log({ err });
      });
```
でupsert動きました🎉

2020-11-18 07:52 UTC, 75asa commented
おおおおおおおおおお！
3150000000000

2020-11-18 09:17 UTC, 75asa commented on src/index.ts
> +  mongoEntityMgr = new MongoEntityManager(connection);
@tk-ozawa  DB成功時に console.log で必要最低限の情報を表示するようにしましょう

2020-11-18 11:07 UTC, 75asa commented on src/index.ts
> +  mongoEntityMgr = new MongoEntityManager(connection);
起動時に error
```
(node:7805) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
```
useUnifiedTopology いらない？

2020-11-19 12:23 UTC, 75asa commented
それと .env と ormconfig 併用してるので大丈夫かなっておもいました @tk-ozawa

2020-11-19 12:24 UTC, 75asa commented
あと user.ts のログが消せない… @usagizmo git 先生ここなんでかわかりますか？

2020-11-19 12:25 UTC, 75asa commented
> あと user.ts のログが消せない… @usagizmo git 先生ここなんでかわかりますか？

@usagizmo これやったのよ、ほんで変更は検知されてんけど…
こんどはどっちともあるやん状態なのよ
https://qiita.com/w-tdon/items/2402464eb833e75794aa

2020-11-24 05:15 UTC, 75asa commented on ormconfig.json
> +  "database": "tl-poilice-man",
```suggestion
  "database": "TL-Police",
```

2020-11-24 05:22 UTC, tk-ozawa commented on ormconfig.json
> +  "database": "tl-poilice-man",
:done:

2020-11-24 05:23 UTC, tk-ozawa commented
@75asa 
DB名変更後動確できました🎉

2020-11-24 06:10 UTC, merged

2020-11-24 06:13 UTC, 75asa reviewed
LGTM

2020-11-24 06:49 UTC, usagizmo commented
@75asa 
通知気づいていませんでした…。
ファイル名の大文字小文字、少し注意必要ですよ。

自分もファイルが2つになった経験があるので、個人的にはこの記事にある設定はおすすめせず、
https://qiita.com/w-tdon/items/2402464eb833e75794aa

`master` ブランチで [ファイルを削除するコミットと、ファイル名を変更したコミットをする] を推奨したいです。
`master` ブランチという条件は、例えばスカッシュマージをした場合、同一PR内で削除コミットと追加コミットをしても、`master` で変更検知できていなかったりするので。

2020-11-24 07:00 UTC, 75asa commented
@usagizmo ありがとうございます！
やっぱそうなんですね〜
アドバイスありがとうございます〜
今回は この PR の webページから小文字のほうをチェックして削除しました